
# =========================================================
#       Actions to be run on all new instances
# ---------------------------------------------------------

- name: Install EPEL release
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: latest

- name: Turn off SELinux
  selinux:
    state: disabled

- name: Perform yum update for all packages
  yum:
    name: '*'
    state: latest

- name: Create local hosts file
  template:
    src: hosts
    dest: /etc/hosts

- name: Check if Service Exists
  stat: path=/etc/init.d/firewalld
  register: service_status

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: service_status.stat.exists